# Packages to remove from fresh and upgraded Omarchy installations
PACKAGES=(
  "typora"
  "typora-debug"
  "dropbox-cli"
  "dropbox"
  "zoom"
  "clipse"
  "clipse-debug"
  "rust"
  "aether"
  "code"
  "alacritty"
)

# Omarchy web apps to remove (desktop files)
WEBAPPS=(
  "Basecamp.desktop"
  "Discord.desktop"
  "Google Contacts.desktop"
  "Google Maps.desktop"
  "Google Messages.desktop"
  "Google Photos.desktop"
  "HEY.desktop"
  "WhatsApp.desktop"
  "X.desktop"
  "YouTube.desktop"
  "Zoom.desktop"
  "typora.desktop"
  "GitHub.desktop"
  "jan.desktop"
  "ChatGPT.desktop"
)
